#############################################################################
# Makefile for building: gameaniaque
# Generated by qmake (2.01a) (Qt 4.6.1) on: sam. 22. sept. 11:57:17 2012
# Project:  gameaniaque.pro
# Template: app
# Command: c:\libs\qt\2010.01\qt\bin\qmake.exe -spec ..\..\Libs\Qt\2010.01\qt\mkspecs\win32-g++ -win32 -o Makefile gameaniaque.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\libs\qt\2010.01\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: gameaniaque.pro  ../../Libs/Qt/2010.01/qt/mkspecs/win32-g++/qmake.conf ../../Libs/Qt/2010.01/qt/mkspecs/qconfig.pri \
		../../Libs/Qt/2010.01/qt/mkspecs/features/qt_functions.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/qt_config.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/exclusive_builds.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/default_pre.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/win32/default_pre.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/debug.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/debug_and_release.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/default_post.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/win32/default_post.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/win32/console.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/win32/rtti.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/win32/exceptions.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/win32/stl.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/shared.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/warn_on.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/win32/thread_off.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/resources.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/uic.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/yacc.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/lex.prf \
		../../Libs/Qt/2010.01/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ..\..\Libs\Qt\2010.01\qt\mkspecs\win32-g++ -win32 -o Makefile gameaniaque.pro
..\..\Libs\Qt\2010.01\qt\mkspecs\qconfig.pri:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\qt_functions.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\qt_config.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\exclusive_builds.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\default_pre.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\win32\default_pre.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\debug.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\debug_and_release.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\default_post.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\win32\default_post.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\win32\console.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\win32\rtti.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\win32\exceptions.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\win32\stl.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\shared.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\warn_on.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\win32\thread_off.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\resources.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\uic.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\yacc.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\lex.prf:
..\..\Libs\Qt\2010.01\qt\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\Libs\Qt\2010.01\qt\mkspecs\win32-g++ -win32 -o Makefile gameaniaque.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
